---
- hosts: "arista7050qx"
  become: true
  gather_facts: no
  vars:
    wpdvlan: "{{ lookup('file','../env/inv-fybvlans.json') | from_json }}"


  tasks: 
    - name: merge VLAN into arista switch
      arista.eos.eos_vlans:
        config:
        - vlan_id: "{{ item.vlan_id }}"
          name:  "{{ item.name }}"
          state: "{{ item.state }}"
        state: "{{ item.ansstate }}"
      when: inventory_hostname in groups['arista7050qx']
      loop:  "{{ wpdvlan }}"
