---
- hosts: "allnetsw"

  gather_facts: no
  vars:
    wpdvlan: "{{ lookup('file','../env/inv-fybvlans.json') | from_json }}"


  tasks: 
    - name: merge VLAN into Cisco switch
      become: false
      cisco.ios.ios_vlans:
        config:
        - vlan_id: "{{ item.vlan_id }}"
          name:  "{{ item.name }}"
          state: "{{ item.state }}"
        state: "{{ item.ansstate }}"
      when: inventory_hostname in groups['ciscocat']
      loop:  "{{ wpdvlan }}"
      async: 1000
      poll: 0

    - name: merge VLAN into Cisco nexus core switch
      become: false
      cisco.nxos.nxos_vlans:
        config:
        - vlan_id: "{{ item.vlan_id }}"
          name:  "{{ item.name }}"
          enabled: true
          state: "{{ item.state }}"
        state: "{{ item.ansstate }}"
      when: inventory_hostname in groups['cisconex']
      loop:  "{{ wpdvlan }}"
      async: 1000
      poll: 0

    - name: merge VLAN into arista switch
      become: true
      arista.eos.eos_vlans:
        config:
        - vlan_id: "{{ item.vlan_id }}"
          name:  "{{ item.name }}"
          state: "{{ item.state }}"
        state: "{{ item.ansstate }}"
      when: inventory_hostname in groups['arista7050qx']
      loop:  "{{ wpdvlan }}"
      async: 1000
      poll: 0