---
- hosts: "allcisco"
  become: false
  gather_facts: no
  vars:
    wpdvlan: "{{ lookup('file','../env/inv-fybvlans.json') | from_json }}"


  tasks: 
    - name: merge VLAN into Cisco switch
      cisco.ios.ios_vlans:
        config:
        - vlan_id: "{{ item.vlan_id }}"
          name:  "{{ item.name }}"
          state: "{{ item.state }}"
        state: "{{ item.ansstate }}"
      when: inventory_hostname in groups['allcisco']
      loop:  "{{ wpdvlan }}"
