---
- hosts: "allcisco"
  become: true
  gather_facts: no

  tasks:
    - name: Gather VLAN data from cisco switch
      cisco.ios.ios_facts:
        gather_subset:
          - "!all"
          - "!min"
        gather_network_resources:
          - vlans
