---
- hosts: "cisconex"

  gather_facts: no
  vars:
    wpdvlan: "{{ lookup('file','../env/inv-fybvlans.json') | from_json }}"


  tasks: 
    - name: merge VLAN into Cisco nexus core switch
      become: true
      cisco.nxos.nxos_vlans:
        config:
        - vlan_id: "{{ item.vlan_id }}"
          name:  "{{ item.name }}"
          state: "{{ item.state }}"
        state: "{{ item.ansstate }}"
      when: inventory_hostname in groups['cisconex']
      loop:  "{{ wpdvlan }}"
      async: 1000
      poll: 0